### ISSUE TITLE
Core dump from recent changes

### ISSUE THREAD

**Issue by ghost** [joeferner/wxNode#2]
On Ubuntu 11.04 getting a core dump with both regenerated bindings or using the ones on github. The version on npm works without an issue but that's prior to a lot of changes it looks like, the webview stuff etc.

**Comment by joeferner** [comment]
wxNode is in the very early stages so it doesn't surprise me all that much that is crashed. I would like to know what caused it and make sure it doesn't happen in the future though.

Could you send me the code or the code you called that caused the error.  

You can also try running

```
gdb --args `which node` yourprogram.js  <--- those are backticks around the which node
run
// wait for the exception
where
```

That should produce a stack trace of the native code.

**Comment by ghost** [comment]
Yeah I was surprised when the one on npm worked at all, so my expectations
are in the right spot.=D I just figured it either might be useful to you in
some way or you might have an easy answer.

**Comment by ghost** [comment]
```
Program terminated with signal 11, Segmentation fault.
#0  0xb7018494 in wxNode_wxPoint::_xGet (name=..., info=...)
    at /home/benvie/node_modules/wxnode/src-generated/wxNode_wxPoint.cpp:258
258       return scope.Close(v8::Number::New(self->x));


/*static*/ v8::Handle<v8::Value> wxNode_wxPoint::_xGet(v8::Local<v8::String> name, const v8::AccessorInfo& info) {
  v8::HandleScope scope;
  wxNode_wxPoint* self = unwrap<wxNode_wxPoint>(info.This());

  return scope.Close(v8::Number::New(self->x));
}
```

Seeing if I can figure out where the abnormality originated

**Comment by ghost** [comment]
Figured it out mostly. My REPL has an option to display [[prototypes]] and apparently something changed between the npm release and this one that is causing them to explode when inspected.
