### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by ghost** [joeferner/wxNode#3]
After a lot of work and fumbling around, I managed to successfully port this to compile and work on Windows, https://github.com/Benvie/wxNode.

**Comment by joeferner** [comment]
Wow! This looks great.

The only problem I see is with (https://github.com/Benvie/wxNode/commit/1a4679d5e387cc9cf91fb24933aacb33aac9e29a) where you are manually removing some methods. Adding an exclusion list to render-template.js might be a better long term solution. I don't mind adding that but I would like to merge the rest of your changes in first. I'm also planning on removing the src-generated directory from source control now that the template rendering is quite fast and part of the mnm build process.

Oh and sorry about the render-template.js code. It started off nice and simple but kept on growing. After I merge these changes I'll try and clean it up a bit.

**Comment by ghost** [comment]
Yeah that was a temporary workaround just to limp over the finish line and get it actually compiled and linked and working. Now that that's done I'm going to go back and revisit those and see what the issue is with them. Figure out whether it's a platform issue or something that broke in my jury rigged process of generating the .xml. Ideally I will come up with an adaption to do that on windows because gccxml I have a feeling isn't ideally suited for the most accurate results analyzing the windows stuff.

**Comment by joeferner** [comment]
Any chance you could submit a pull request? Looks like what you've done is really good.

**Comment by joeferner** [comment]
I've been trying to build it on windows but I'm not having a whole lot of luck.  I keep getting "cannot convert parameter 2 from 'LPCTSTR' to 'LPCWSTR'" which after doing some research it has to do with the /D_UNICODE flag which looks like it's in there.  Hopefully I'll get some more time to work on it this week.

**Comment by ghost** [comment]
Yeah a lot of my time was spent in converting to use unicode. Since wxWidgets switched to an all unicode build that imposes some consequences for Windows. A lot of windows API calls are actually two separtate calls, one ending in W and one ending in A. Basically any involving strings, or Ansi and Wide. When compiling in say Visual Studio it makes sure to match everything up correctly but obviously we're way out in the cornfields and have to manage everything ourself.

That error is coming up because somewhere during either the compile process process of wx or of the module a flag that turns on unicode isn't being set. The unicode settings need to match up. I thought that I had managed to centralize all the places this was needed and made them part of the included build process, but I must have missed something, so I'll take a look and see.

**Comment by ghost** [comment]
Oh one note is that I'm pretty sure the whole unicode in wx thing is a currently moving target, so make sure you have the latest version. I think some changes within the week before i published this code may have affected this specific issue.

**Comment by ghost** [comment]
Also here's the compiled .node file that should work, as a reference. https://github.com/downloads/Benvie/wxNode/wxnode_bindings.node

**Comment by joeferner** [comment]
code is now compiling on windows with instructions in README.md
